### ISSUE TITLE
Error while Lint Trigger after Change

### ISSUE THREAD

**Issue by ghost** [pchomik/linter-python#16]
Thanks for the amazing package!

The error appears only when the Lint Trigger includes a 'Change' option. Linting works otherwise and there are no issue when it's set to Lint only after Save. Every time I type I get one or more of the following errors:

TypeError: Path must be a string. Received null
    at assertPath (path.js:8:11)
    at Object.posix.join (path.js:477:5)
    at LinterPython.lint (/home/user/.atom/packages/linter-python/lib/linter-python.js:54:44)
    at promises.push.Promise.then._this.emitter.emit.linter (/home/user/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /home/user/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/home/user/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /home/user/.atom/packages/linter/lib/linter.coffee:98:16
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /home/user/.atom/packages/linter/lib/editor-linter.js:80:22
    at /home/user/.atom/packages/linter/lib/helpers.coffee:23:18

**Comment by pchomik** [comment]
@JLCCI What atom and plugin version you are using?

**Comment by pchomik** [comment]
I made few tests with atom 1.5.4 and plugin 2.1.6 and I can't reproduce your problem. Please try update plugin because error looks similar to something what was fixed in 2.1.6 version.

**Comment by ghost** [comment]
Thanks for a prompt reply. I have a fresh install of both Atom (1.6.0-1, stable) and linter-python (2.1.6) on Linux. Perhaps it has something to do with a newer version of Atom?

**Comment by pchomik** [comment]
I found the place where bug could appear. Problem may appear if project is not available in atom editor but only file is opened. I will fix that in 2.1.7.

Workaround for now: Please open directory where edited file is available. Problem should disappear.

**Comment by ghost** [comment]
That seems to fix the problem, thanks for the quick workaround. Looking forward to the updated version of the package, it's amazingly useful!

**Comment by pchomik** [comment]
Could you retry with latest version and after editor restart? I was able to reproduce your problem and problem disappers after last commit. 

In case of error please paste full error message from 2.1.7 plugin.

**Comment by ghost** [comment]
Apologies, restart solved the problem. :) Thank you.
