### ISSUE TITLE
ENOENT:  no such file or directory !

### ISSUE THREAD

**Issue by boubouhkarim** [pchomik/linter-python#21]
Hi,
i got this message window every time i save my python file

`ENOENT: no such file or directory, open '/tmp/input116410-1311-g9h5ic'
ENOENT: no such file or directory, open '/tmp/input116410-1311-g9h5ic'
Hide Stack Trace
Error: ENOENT: no such file or directory, open '/tmp/input116410-1311-g9h5ic'
    at Error (native)
`

**Comment by pchomik** [comment]
Could you check your case with plugin option "Lint Trigger" set to "Lint only after save" ?

**Comment by boubouhkarim** [comment]
Thanks, for replaying, 
The `Lint Trigger` option is already set to "`Lint only after save`". _i'm keeping the default options_
i got this error when saving python file with some errors or warning.

i don't have any problems with the /tmp folder in my Archlinux.

the plugin try to create a new file each time there is new errors on the file
for example
`ENOENT: no such file or directory, open '/tmp/input116410-19256-zyp844`
`ENOENT: no such file or directory, open '/tmp/input116410-19256-1xottsh'`
......

**Comment by pchomik** [comment]
Today I had the same situation. Problem disappear after project change. IMO this is related to project and file location.

**Comment by pchomik** [comment]
I tried to reproduce your error and I can't. @boubouhkarim do you have this error?
If yes please set "debug" flag in plugin and provide output from dev tools console.

**Comment by boubouhkarim** [comment]
hi,
i made a noise.py file, andi checked the atom debugger, there is no weird things :
`

```
linter-python.js:115 [Linter-Python] Project dir: /home/karim/OpenXC/Graph/DriverGraph
linter-python.js:141 [Linter-Python] Pylama path looks ok.
linter-python.js:78 [Linter-Python] Command: /usr/bin/pylama
linter-python.js:79 [Linter-Python] Arguments: -f,pep8,/home/karim/OpenXC/Graph/DriverGraph/noise.py
linter-python.js:86 [Linter-Python] Raw output 
 noise.py:10:1: E0602 undefined name 'ddd' [pyflakes]
noise.py:11:1: E0602 undefined name 'd' [pyflakes]
noise.py:37:80: E501 line too long (105 > 79 characters) [pep8]
noise.py:43:80: E501 line too long (137 > 79 characters) [pep8]

linter-python.js:88 [Linter-Python] Output: 
 noise.py:10:1: E0602 undefined name 'ddd' [pyflakes],noise.py,10,1,E0602,undefined name 'ddd' [pyflakes],noise.py:11:1: E0602 undefined name 'd' [pyflakes],noise.py,11,1,E0602,undefined name 'd' [pyflakes],noise.py:37:80: E501 line too long (105 > 79 characters) [pep8],noise.py,37,80,E501,line too long (105 > 79 characters) [pep8],noise.py:43:80: E501 line too long (137 > 79 characters) [pep8],noise.py,43,80,E501,line too long (137 > 79 characters) [pep8]
linter-python.js:201 [Linter-Python] New message: 
    type: Error
    text: E0602 undefined name 'ddd' [pyflakes]
    filePath: /home/karim/OpenXC/Graph/DriverGraph/noise.py
    range: 9,0,9,3
linter-python.js:201 [Linter-Python] New message: 
    type: Error
    text: E0602 undefined name 'd' [pyflakes]
    filePath: /home/karim/OpenXC/Graph/DriverGraph/noise.py
    range: 10,0,10,1
linter-python.js:201 [Linter-Python] New message: 
    type: Error
    text: E501 line too long (105 > 79 characters) [pep8]
    filePath: /home/karim/OpenXC/Graph/DriverGraph/noise.py
    range: 36,0,36,105
linter-python.js:201 [Linter-Python] New message: 
    type: Error
    text: E501 line too long (137 > 79 characters) [pep8]
    filePath: /home/karim/OpenXC/Graph/DriverGraph/noise.py
    range: 42,0,42,137
```

`

but i still have this nice modals
check this pictures to have ab idea what i'm talking about 

http://i.imgur.com/qtoxvrS.png

Thanks for the great and very helpful plugin (y)

**Comment by pchomik** [comment]
1. There is button "Show stack trace". Please show this stack trace.
2. Could you try to move your .atom folder and try with fresh atom installation with linter-plugin only.

**Comment by pchomik** [comment]
Any update ?

**Comment by boubouhkarim** [comment]
Hi
i'm sorry, i was a little bit out.

i tried to reproduce the error with the same old project, but i couldn't get this errors,

i didn't change much, but i keep installing updates, you know about Archlinux.

so my be the latest version of Atom has fixed the problem.

I'll notify you if there is any news about this bug

**Comment by pchomik** [comment]
Issue is not visible now. Please reopen ticket is problem appears.
