### ISSUE TITLE
links for error codes?

### ISSUE THREAD

**Issue by linickx** [pchomik/linter-python#22]
[Feature Request] 

Is it possible to make the error codes hyperlinks (_clickable_)?

![python-linter](https://cloud.githubusercontent.com/assets/649661/15217025/91f2e0d0-1851-11e6-8f25-9596304f4831.png)

The [implementation in linter-shellcheck](https://github.com/AtomLinter/linter-shellcheck/blob/master/lib/main.coffee#L7) works really well....

![shellcheck-linter](https://cloud.githubusercontent.com/assets/649661/15217032/98683b04-1851-11e6-8b60-f8deaeea1910.png)

Thx.

**Comment by pchomik** [comment]
Hi,

Feature accepted. Api allows for that and shoud be easy to add some links.

**Comment by pchomik** [comment]
I found that pylama errors are distributed across multiple projects e.g
- pep8: http://pep8.readthedocs.io/en/latest/intro.html#error-codes
- pep257: http://pydocstyle.readthedocs.io/en/latest/error_codes.html
- pyflakes (flake8): http://flake8.readthedocs.io/en/latest/warnings.html
- pylint - ???
  If you look into project documentation most problems are described by one line sentence.

What kind of hyperlink you would like to get?
Would you like to create wiki page and collect codes from all pylama projects  with description and examples like in shellchecker?

**Comment by linickx** [comment]
Hi, I don't mind helping with that. I guess you just need to set a standard. 

IMHO the choices are either a wiki page per error. e.g.
- title: pep8 E101 url: `pchomik/linter-python/wiki/pep8-e101`
- title: pep8 E121 url: `pchomik/linter-python/wiki/pep8-e121`
- title: flake8 F401 url: `pchomik/linter-python/wiki/flake8-f401`
- title: flake8 F823 url: `pchomik/linter-python/wiki/flake8-f823`

or one wiki page, with a `H1` per error which like so...
- title: pep8 
  - `<h1>E101</h1>` url: `pchomik/linter-python/wiki/pep8#e101`
  - `<h1>E121</h1>` url: `pchomik/linter-python/wiki/pep8#e121`
- title: flake8 
  - `<h1>F401</h1>` url: `pchomik/linter-python/wiki/flake8#f401`
  - `<h1>F823</h1>` url: `pchomik/linter-python/wiki/flake8#f823`

... I guess the later is easier as the source errors / documentation is already in .rst so it should be a simple copy/paste affair.

Thoughts?

**Comment by pchomik** [comment]
I'd like to have pages per tool. Error codes may overlap.
I'd like to start with .rst or .md file from the beginning. I will be able to create basic structure for this feature but whole content must be created by community via pull requests.
I think I will be able to show something next week. Let's see.

**Comment by linickx** [comment]
> I'd like to have pages per tool. Error codes may overlap.

Actually that's what I meant :flushed:

> I'd like to start with .rst or .md file from the beginning. I will be able to create basic structure for this feature but whole content must be created by community via pull requests.

As Wiki's are .md repo's in github; to get you started, I have created [pep8](https://github.com/linickx/test/wiki/pep8) and [flake8](https://github.com/linickx/test/wiki/flake8) in my test repo, a bit of regex on the rst to make markdown wasn't that painful.

**Comment by pchomik** [comment]
Some time ago I made decision to put documentation into separate project (https://github.com/pchomik/linter-python-doc) because images size was much more bigger than whole plugin code. We can use it to put error codes documentation.

If you like you can add .md files there as pull request. Than everyone will be able to join (User cannot create pull request for Wiki on github).

At least this is my plan.

**Comment by linickx** [comment]
Hi, Last `.md` created in PR pchomik/linter-python-doc#3 , you should be good to go 😎

**Comment by pchomik** [comment]
Thanks a lot. I have more than enough to start.

**Comment by pchomik** [comment]
Change available in 3.0.4
