### ISSUE TITLE
Plugin should return null if validation was not executed

### ISSUE THREAD

**Issue by pchomik** [pchomik/linter-python#28]
In current state plugin returns empty array if linter exit without validation. After that linter cleans all errors. IMO old errors should stay if validation was not executed. 

There are at least two solutions: 
1. Remember errors and return them if validation was not triggered
2. Return null if validation was not triggered

First investigation shows no impact when null is returned. I will double check this behavior during implementation.

**Comment by Arcanemagus** [comment]
Just a note that `linter` itself keeps track of the messages, returning `null` should be sufficient. Is that going to cause any issues @steelbrain?

**Comment by steelbrain** [comment]
@Arcanemagus Returning `null` has the same effect as returning an empty array. If he wants the errors to stay if the validation was not run, he should store the last results in a var and return that var instead of null

**Comment by pchomik** [comment]
I can introduce some kind cache functionality and return previous result. In other hand I did small test and returning null value has different effect than empty array. Linter cleans previous messages if empty result is returned and do nothing when null is returned. 
During my 3 days test I was not able to find any side effect. 
What is your idea/recommendation?

**Comment by steelbrain** [comment]
Which version of linter are you using? It's really odd that linter doesn't clear previous results when you give it null, I don't remember writing that functionality

**Comment by pchomik** [comment]
The linter version is 1.11.14

**Comment by steelbrain** [comment]
Wow, you're right. Thanks for the report man, don't know how it slipped under my radar. I've pushed the fix and it'll be included in the linter major linter release (major because we don't want to break current behavior)

**Comment by pchomik** [comment]
Now decision is simple. I will adapt plugin.

**Comment by steelbrain** [comment]
Yeah sorry we have to keep the unexpected behavior count low to resolve any confusions. Because while you knew returning null doesn't update result, any other person would think it equals empty array aka no result. So doing this will now allow consistent behavior and less confusion, hope it makes sense :)

**Comment by pchomik** [comment]
No problem. I understand the reason. Plugin change was simple and is almost ready.

**Comment by pchomik** [comment]
3.0.5 released
