### ISSUE TITLE
Errors missing from panel

### ISSUE THREAD

**Issue by Bibliofile** [pchomik/linter-python#29]
I'm not sure what's causing this issue, other linter-\* packages are correctly showing errors & warnings. Please let me know if I'm missing something obvious. linter-pep8 works, but I would rather use this package due to the options provided.

The package, so far as I can tell, correctly gathers the required errors.

Windows 10
pylama 7.1.0
python 3.5.2

![capture](https://cloud.githubusercontent.com/assets/6462247/18414987/269c0ce2-779e-11e6-9c5e-ccfdaebc8ffc.PNG)

Installed packages:
autocomplete-python
linter
linter-jshint
linter-php
linter-python
minimap
minimap-split-diff
symbol-gen

**Comment by pchomik** [comment]
IMO this is related to column number. Calculated value for atom is -1. Probably is invalid.
I'm not sure why atom did not display error about invalid number but I will check that.

**Comment by pchomik** [comment]
I used latest atom and your environment and I don't see a problem. 
Could you use code form #30 pull request (or issue29 branch) and provide new debug logs?

**Comment by pchomik** [comment]
Cannot reproduce
