### ISSUE TITLE
"Execution finished with error" notification when file has bad indent

### ISSUE THREAD

**Issue by RenaKunisaki** [pchomik/linter-python#31]
If a class method, having a docstring more than one line long, is indented too far, an error message notification is shown every time the file is saved (even if not modified).

Test case: (notice `def foo` is indented one tab too far)
```
#!/usr/bin/env python3

class Test:

        def foo(bar):
        """A docstring,
        with more than one line.."""
        return 0

# Error message notification appears when saving this file
# with `foo` incorrectly indented:
# Execution finished with error:
# Error: Column start (59) greater than line length (36)
```

The message goes away when `linter-python` package is disabled.

**Comment by pchomik** [comment]
Thanks for report. I will look into this next week.

**Comment by tcawlfield** [comment]
I see
> Execution finished with error:
> Error: exited with code 1

any time there are any errors or recommendations found by pylama. I don't yet see when/if exit codes were implemented in pylama, but runner.ts (using child-process-es6-promise) handles non-zero exit codes as an exception. I don't know enough Javascript to fix this myself, but I can hack pylama to always exit with 0. When I do that the problem goes away.

**Comment by pkopac** [comment]
I can confirm. Getting the same error, no linting in the editor. When I run debug mode, extract the command and run it in the console, it works as expected. Output from windows cmd follows:
```
C:\Users\pkopac>pylama --sort E,W,D -f pep8 C:\Users\pkopac\tmp\errors.py
tmp\errors.py:3:1: E302 expected 2 blank lines, found 1 [pycodestyle]
tmp\errors.py:6:1: E302 expected 2 blank lines, found 1 [pycodestyle]
tmp\errors.py:9:1: E302 expected 2 blank lines, found 1 [pycodestyle]

C:\Users\pkopac>echo Exit Code is %errorlevel%
Exit Code is 1
```

**Comment by Zebradil** [comment]
#34 fixed it for me.

**Comment by pchomik** [comment]
New version of plugin was released.
