### ISSUE TITLE
Docstring pep257 are often contradictory

### ISSUE THREAD

**Issue by PaulEcoffet** [pchomik/linter-python#35]
There are several case of warnings that are contradictory with pep257.

For instance, D203 "1 blank line required before class docstring" and D211 "No blank lines allowed before class docstring" are mutually exclusive.

It is also the case for D212 "Multi-line docstring summary should start at the first line" and D213 "Multi-line docstring summary should start at the second line".

I have therefore no idea of what are the best practices for docstring or if it even matters.

**Comment by pchomik** [comment]
Pylama uses pydocstyle lib to check pep257. Could you run command 
```
pydocstyle  your_file.py
```
and confirm if mentioned problems appear?

**Comment by PaulEcoffet** [comment]
Here is the output I got:

```console
➔ pylama hill_climbing.py --linters pep257,pycodestyle,pyflakes,pep8,pydocstyle
hill_climbing.py:10:1: D212 Multi-line docstring summary should start at the first line [pep257]
hill_climbing.py:10:1: D212 Multi-line docstring summary should start at the first line [pydocstyle]

// After correction of the error

➔ pylama hill_climbing.py --linters pep257,pycodestyle,pyflakes,pep8,pydocstyle
hill_climbing.py:10:1: D213 Multi-line docstring summary should start at the second line [pep257]
hill_climbing.py:10:1: D213 Multi-line docstring summary should start at the second line [pydocstyle]

➔ pylama hill_climbing.py --linters pep257,pycodestyle,pyflakes,pep8           
hill_climbing.py:10:1: D213 Multi-line docstring summary should start at the second line [pep257]

➔ pydocstyle hill_climbing.py 
*no output*
```

I am using Pylama 7.3.3. I think the issue is coming from there. Thank you for your help.

**Comment by pchomik** [comment]
@PaulEcoffet Could you report this issue in pylama project and close it here ?
