### ISSUE TITLE
Not showing anything

### ISSUE THREAD

**Issue by blakawk** [pchomik/linter-python#36]
Just followed installation instruction and nothing works. Enabling debug information show that pylama is correctly running on my files and detectings issues, but nothing is shown in Atom.

linter-python 3.1.1
linter 2.1.0
linter-ui-default 1.2.1
atom 1.15.0
![atom](https://cloud.githubusercontent.com/assets/1149069/24200705/3aa073c4-0f0e-11e7-919a-0027b1ed3d0a.png)

**Comment by pchomik** [comment]
@blakawk could you check with latest version?

**Comment by blakawk** [comment]
@pchomik I just checked still nothing displayed. It seems to me that the issue is coming from the fact that, on Win32 platforms, pylama.exe output is separated with CRLF, while the plugin seems to expect LF to parse the messages.

Version information:
Python 3.5.2
pylint-1.7.1
pylama-7.3.3
pylama-pylint-3.0.1
Atom 1.17.0 ia32
linter-python 3.1.2
linter 2.1.4
linter-ui-default 1.6.0
