### ISSUE TITLE
Error running Python Linter TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by c2xbrhdj6u4qs15** [pchomik/linter-python#37]
Hi,

I am getting the following console Error "**[Linter] Error running Python Linter TypeError: Cannot read property 'getPath' of undefined(…)(anonymous function) @ /Users/username/.atom/packages/linter/lib/linter-registry.js:177**".

OS: OS X El Capitan 10.11.6
Atom Version: 1.15.0 (x64)
Installed Packages:
Community Packages (24) /Users/username/.atom/packages
├── atom-beautify@0.29.17
├── atom-clock@0.1.6
├── atom-runner@2.7.1
├── autocomplete-python@1.8.62
├── busy-signal@1.3.0
├── file-icons@2.1.1
├── git-plus@7.3.3
├── git-time-machine@1.5.6
├── intentions@1.1.2
├── linter@2.1.2
├── linter-eslint@8.1.4
├── linter-jscs@4.1.2
├── linter-jshint@3.0.3
├── linter-jsonlint@1.3.0
├── linter-python@3.1.1
├── linter-python-pep8@0.2.0
├── linter-shellcheck@1.4.4
├── linter-ui-default@1.2.1
├── minimap@4.26.8
├── minimap-split-diff@0.3.7
├── platformio-ide-terminal@2.5.0
├── python-autopep8@0.1.3
├── script@3.14.1
└── split-diff@1.2.1

Please let me know if you require more information and I'll provide it.

Regards

**Comment by c2xbrhdj6u4qs15** [comment]
Hi,

Issue still persists, getting the following error message in the Atom Console:

[Linter] Error running Python Linter TypeError: Cannot read property 'getPath' of undefined(…)(anonymous function) @ linter-registry.js [sm]:144linter-registry.js [sm]:144 [Linter] Error running Python Linter TypeError: Cannot read property 'getPath' of undefined(…)(anonymous function) @ linter-registry.js [sm]:144

Thanks in advance.

Regards

**Comment by pchomik** [comment]
Could you check code from #40 pull request?

**Comment by c2xbrhdj6u4qs15** [comment]
Hi,

Are suggesting to replace the following Line in "src/linter.ts":

`let textEditor = atom.workspace.getActiveTextEditor();`

with:

`let textEditor = atom.workspace.isTextEditor(textEditor);`

Regards

**Comment by pchomik** [comment]
Thanks for proposition. Does code from #40 pull request fix your issue?

**Comment by c2xbrhdj6u4qs15** [comment]
I updated Atom to Version 1.16.0 and replaced the following line in the src/linter.ts as suggested in [#40](https://github.com/pchomik/linter-python/pull/40):

`let textEditor = atom.workspace.getActiveTextEditor();`
with:
`let textEditor = atom.workspace.isTextEditor(textEditor);`

So far no error's, but needs further testing.

Regards

**Comment by MatteoRagni** [comment]
For me it still raises an error, due to the fact that [`lib/linter.js:27`](https://github.com/pchomik/linter-python/blob/master/lib/linter.js#L27) is `undefined` if the current active tab is not a TextEditor (for example, I open the editor and the tab is the setting tab). It should be checked if `textEditor` is `undefined`, before running `getPath`.

**Comment by Arcanemagus** [comment]
@MatteoRagni The code in #40 specifically adds a check against that.

**Comment by c2xbrhdj6u4qs15** [comment]
Issue still persisted even after I installed the suggested fix. I just got fed up and uninstalled the package. Now I am using package linter-flake8 and all works fine.

**Comment by MatteoRagni** [comment]
@Arcanemagus no the code in #40 does not fix the issue, that it is still present when dealing with settings tab.

**Comment by razerraz** [comment]
I have the same issue, but only on a virtual folder linked to sftp access (gnome gvfs mount)
On local hard drive it seems to work as espected on validation
If it can help...

**Comment by pchomik** [comment]
I was able to reproduce only simplest case. After change in #40 I'm not able to generate case where getPath error appears. I will release new version of the plugin.

It will be great if you could update plugin after release and test your case one more time.

**Comment by pchomik** [comment]
New version was released: 3.1.2
