### ISSUE TITLE
Uncaught (in promise) Error: Line number (322) greater than maximum line (321)

### ISSUE THREAD

**Issue by c2xbrhdj6u4qs15** [pchomik/linter-python#41]
Hi,

I am also getting this error in the Console:

/Users/username/.atom/packages/linter-python/node_modules/atom-linter/lib/index.js:165 Uncaught (in promise) Error: Line number (322) greater than maximum line (321)(…)

Not sure if this is related to the other issues [(#37)](https://github.com/pchomik/linter-python/issues/37) I opened.

Regards

**Comment by pchomik** [comment]
I can image such case when you use option lint trigger "File modified".
Plugin returns error about line 322 but in the middle of communication between linter-python and linter line 322 was removed. Than such error may appear.

I'm not sure if I can do anything about this.

@c2xbrhdj6u4qs15 can you describe scenario to help to reproduce issue?

**Comment by c2xbrhdj6u4qs15** [comment]
No worries. The issue described above appeared after an update of either linter or linter-python. You can close this Issue, since the error doesn't appear anymore.
