### ISSUE TITLE
Adding isort support

### ISSUE THREAD

**Issue by ghost** [pchomik/linter-python#42]
Great work with the linter! Any chance of adding isort check as is implemented in linter-pylama? I don't mean the isort function (thought that would be great) but rather isort error highlighting.

**Comment by pchomik** [comment]
Implementation looks simple but I cannot promise when it will be added. Please cross the fingers.

**Comment by ghost** [comment]
Many thanks for considering this!

**Comment by ghost** [comment]
Any progress of this? I think we could borrow the code from python-pylama which has it built-in.

**Comment by ghost** [comment]
Since linter-pylama has it there is probably no point in adding it here. Thanks!
